dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
before_install:
  - chmod +x mvnw
before_script:
  - psql -c "CREATE USER simpleapi WITH PASSWORD 'q1w2e3r4';" -U postgres
  - psql -c "CREATE DATABASE db_lab1 OWNER simpleapi;" -U postgres
